### File directories ###
data_directory: "mnt/c/Users/ibhat/repo/grad_school/rob530/ford-av-ogm-continuous-csm/data/"
rosbag_directory: '/mnt/c/Users/ibhat/repo/grad_school/rosbags/Sample-Data.bag'
